# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build docker

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
     - uses: actions/checkout@v2
     - name: build-push
       uses: docker/build-push-action@v1
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         registry: docker.io
         repository: valm13/mywebserver
         tag_with_sha: true
      
    # - name: Configure my AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
     #    aws-access-key-id: ASIAZB53AQAN2RUMWHBP
     #    aws-secret-access-key: snnaF+O0wv2Sq0FEwJ/qnPWrjgUWacKaghJYwlWl
    #     aws-region: us-east-1
        
  #   - name: Deploy AWS Ressources
   #    run: aws cloudformation deploy --template-file cloudformation.yaml --stack-name valm13-stack --region us-east-1
