# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build docker

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
     - uses: actions/checkout@v2
     
     - uses: minchao/cfn-nag-action@master
       with:
         args: '--input-path cf-all.yaml'
        
     - name: build-push
       uses: docker/build-push-action@v1
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         registry: docker.io
         repository: valm13/mywebserver
         tags: v1
         tag_with_sha: true
         
     - name: prepare-kustomize
       run: |
         sed -i "s#IMAGE_NAME#allanduee/ssc#g" kustomization.yaml
         sed -i "s/IMAGE_TAG/sha-$(git rev-parse --short HEAD)/g" kustomization.yaml
         cat kustomization.yaml
        
     - name: Deploy AWS Ressources
       run: |
         aws configure set default.region us-east-1
         aws configure set default.output json
         aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
         aws cloudformation deploy --template-file cloudformation.yaml --stack-name valm13-stack --no-fail-on-empty-changeset
         
     - name: deploy-to-k8s
       run: |
         aws eks update-kubeconfig --name isen-2
         kubectl kustomize . | kubectl apply -f -
                  
     - name: deploy-to-aws
       run: |
         aws cloudformation deploy --template-file ecs-task.yaml --stack-name ecs-task --parameter-overrides ImageName=docker.io/valm13/mywebserver:sha-$(git rev-parse --short HEAD) --no-fail-on-empty-changeset
