# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build docker

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
     - uses: docker/checkout-action@v1
     - name: build-push
       uses: docker/build-push-action@v1
       with:
         username: ${{ DOCKER_USERNAME }}
         password: ${{ DOCKER_PASSWORD }}
         registry: docker.io
         repository: valm13/mywebserver
         tag_with_sha: true
